# Generated by Django 5.2.17 on 2026-09-30 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(help_text='控制指令種類，如 backup_reserve, operation_mode', max_length=64)),
                ('parameters', models.JSONField(default=dict, help_text='指令參數內容')),
                ('status', models.CharField(choices=[('PENDING', '處理中'), ('SUCCESS', '執行成功'), ('FAILED', '執行失敗')], default='PENDING', max_length=32)),
                ('tesla_command_id', models.CharField(blank=True, help_text='Tesla 官方回應指令 ID', max_length=128, null=True)),
                ('tesla_response', models.JSONField(blank=True, default=dict, help_text='Tesla API 回傳完整原始 JSON')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.CASCADE, related_name='control_logs', to='sites.site')),
            ],
            options={
                'db_table': 'control_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
