# Generated by Django 5.2.17 on 2026-09-30 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True, help_text='採集時間戳記')),
                ('solar_kw', models.FloatField(default=0.0, help_text='太陽能功率 (kW)')),
                ('grid_kw', models.FloatField(default=0.0, help_text='電網功率 (kW, 負值為回售)')),
                ('battery_kw', models.FloatField(default=0.0, help_text='電池功率 (kW, 正值充電, 負值放電)')),
                ('home_kw', models.FloatField(default=0.0, help_text='家庭負載用電 (kW)')),
                ('soc_pct', models.FloatField(default=0.0, help_text='電池電量百分比 (%)')),
                ('grid_status', models.CharField(default='Connected', max_length=32)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='sites.site')),
            ],
            options={
                'db_table': 'telemetry_records',
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['site', '-time'], name='telemetry_r_site_id_71e21f_idx')],
            },
        ),
    ]
