# Generated by Django 5.2.17 on 2026-09-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.CharField(help_text='案場識別碼，如 site_01', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='案場名稱', max_length=128)),
                ('teg_ip', models.CharField(default='192.168.1.100', help_text='案場 TEG 區域網路 IP', max_length=64)),
                ('battery_capacity_kwh', models.FloatField(default=13.5, help_text='電池額定總容量 (kWh)')),
                ('max_solar_kw', models.FloatField(default=10.0, help_text='太陽能最大裝置容量 (kW)')),
                ('timezone', models.CharField(default='Asia/Taipei', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sites',
                'ordering': ['site_id'],
            },
        ),
    ]
